name: Build

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build
        run: |
          msbuild src/FanControl.LianLiPlugin.sln /p:Configuration=Release /p:Platform="Any CPU"
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          Copy-Item "src\bin\Release\FanControl.LianLiPlugin.dll" "artifacts\"

      - name: Build ARGB
        run: |
          msbuild src/FanControl.LianLiPlugin.sln /p:Configuration=Release /p:Platform="Any CPU" /p:DefineConstants="TRACE%3BARGB" /p:AssemblyName=FanControl.LianLiPlugin.ARGB
          Copy-Item "src\bin\Release\FanControl.LianLiPlugin.ARGB.dll" "artifacts\"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: FanControl.LianLiPlugin
          path: artifacts/
